# Generated by Django 2.0.4 on 2018-08-02 18:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('idBodega', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=100, verbose_name='Ubicacion')),
            ],
            options={
                'verbose_name': 'bodega',
                'verbose_name_plural': 'bodegas',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField(verbose_name='Monto')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='fecha')),
            ],
            options={
                'verbose_name': 'cotizacion',
                'verbose_name_plural': 'cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('idOrden', models.IntegerField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=100, verbose_name='Ubicacion')),
            ],
            options={
                'verbose_name': 'obra',
                'verbose_name_plural': 'obras',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('rut', models.IntegerField(verbose_name='RUT')),
                ('cargo', models.CharField(choices=[('PO', 'Personal de obra'), ('EC', 'Encargado de Compras'), ('BG', 'Bodeguero')], default='PO', max_length=2, verbose_name='Cargo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=400, verbose_name='Descripción del producto')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('precio', models.IntegerField(verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
            },
        ),
        migrations.CreateModel(
            name='ProductoEnBodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Bodega')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Producto')),
            ],
        ),
    ]
