# Generated by Django 2.0.4 on 2018-08-06 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_delete_cotizacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoenpedido',
            options={'verbose_name': 'Producto en pedido', 'verbose_name_plural': 'Productos en Pedidos'},
        ),
    ]
