# Generated by Django 2.0.4 on 2018-08-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_pedido_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productoenbodega',
            options={'verbose_name': 'bodega', 'verbose_name_plural': 'bodegas'},
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(choices=[('PO', 'Personal de obra'), ('EC', 'Encargado de Compras'), ('BG', 'Bodeguero'), ('AD', 'Admin')], default='PO', max_length=2, verbose_name='Cargo'),
        ),
    ]
